# Generated by Django 5.2.1 on 2025-11-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_userprofile_location_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="social_twitter",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
