# Generated by Django 5.0.6 on 2026-04-04 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={"ordering": ["-created"]},
        ),
    ]
