# Generated by Django 5.2.1 on 2025-11-04 19:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Authors",
            fields=[
                ("name", models.CharField(max_length=202)),
                ("age", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
