# Generated by Django 5.2.1 on 2025-11-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_project_review_tags_delete_authors_delete_book_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="featured_image",
            field=models.ImageField(
                blank=True, default="default.jpg", null=True, upload_to=""
            ),
        ),
    ]
