# Generated by Django 5.2.1 on 2025-11-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_project_owner"),
        ("users", "0003_userprofile_location_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="owner",
            field=models.ManyToManyField(to="users.userprofile"),
        ),
    ]
