# Generated by Django 5.0.6 on 2026-02-19 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0008_alter_project_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-vote_total"]},
        ),
    ]
